feed/models.py
from mongoengine import CASCADE
from flask import url_for
import os

from app import db
from utilities.common import utc_now_ts_ms as now
from user.models import User
from utilities.common import linkify, ms_stamp_humanize
from settings import STATIC_IMAGE_URL, AWS_BUCKET, AWS_CONTENT_URL

POST = 1
COMMENT = 2
LIKE = 3

MESSAGE_TYPE = (
    (POST, 'Post'),
    (COMMENT, 'Comment'),
    (LIKE, 'Like'),
    )

class Message(db.Document):
    from_user = db.ReferenceField(User, db_field="fu", reverse_delete_rule=CASCADE)
    to_user = db.ReferenceField(User, db_field="tu", default=None, reverse_delete_rule=CASCADE)
    text = db.StringField(db_field="t", max_length=1024)
    live = db.BooleanField(db_field="l", default=None)
    create_date = db.LongField(db_field="c", default=now())
    parent = db.ObjectIdField(db_field="p", default=None)
    images = db.ListField(db_field="ii")
    message_type = db.IntField(db_field='mt', default=POST, choices=MESSAGE_TYPE)
    
    @property
    def text_linkified(self):
        return linkify(self.text)
        
    @property
    def human_timestamp(self):
        return ms_stamp_humanize(self.create_date)
        
    @property
    def comments(self):
        return Message.objects.filter(parent=self.id, message_type=COMMENT).order_by('create_date')

    @property
    def likes(self):
        return Message.objects.filter(parent=self.id, message_type=LIKE).order_by('-create_date')
        
    def post_imgsrc(self, image_ts, size):
        if AWS_BUCKET:
            return os.path.join(AWS_CONTENT_URL, AWS_BUCKET, 'posts', '%s.%s.%s.png' % (self.id, image_ts, size))
        else:
            return url_for('static', filename=os.path.join(STATIC_IMAGE_URL, 'posts', '%s.%s.%s.png' % (self.id, image_ts, size)))
    
    meta = {
        'indexes': [('from_user', 'to_user', '-create_date', 'parent', 'message_type', 'live')]
    }
    
class Feed(db.Document):
    user = db.ReferenceField(User, db_field="u", reverse_delete_rule=CASCADE)
    message = db.ReferenceField(Message, db_field="m", reverse_delete_rule=CASCADE)
    create_date = db.LongField(db_field="c", default=now())
    
    meta = {
        'indexes': [('user', '-create_date')]
    }

feed/forms.py
from flask_wtf import FlaskForm
from wtforms import validators, StringField
from wtforms.widgets import TextArea
from flask_wtf.file import FileField, FileAllowed

class FeedPostForm(FlaskForm):
    images = FileField(
        'Select images',
        render_kw={'multiple': True},
        validators=[
            FileAllowed(['jpg', 'jpeg', 'png', 'gif'], 'Only JPEG, PNG and GIFs allowed')
            ]
        )
    post = StringField('Post',
        widget=TextArea(),
        validators=[
            validators.DataRequired(),
            validators.Length(max=1024)
            ]
        )

feed/views.py
from flask import Blueprint, request, session, redirect, url_for, abort, render_template
from werkzeug import secure_filename
import os

from user.decorators import login_required
from user.models import User
from feed.models import Message, Feed, POST, COMMENT, LIKE
from feed.process import process_message
from feed.forms import FeedPostForm
from settings import UPLOAD_FOLDER
from utilities.imaging import image_height_transform

feed_app = Blueprint('feed_app', __name__)

@feed_app.route('/message/add', methods=('GET', 'POST'))
@login_required
def add_message():
    ref = request.referrer
    form = FeedPostForm()
    
    if form.validate_on_submit():
        # process images
        post_images = []
        uploaded_files = request.files.getlist('images')
        if uploaded_files and uploaded_files[0].filename != '':
            for file in uploaded_files:
                filename = secure_filename(file.filename)
                file_path = os.path.join(UPLOAD_FOLDER, 'posts', filename)
                file.save(file_path)
                post_images.append(file_path)
                
        # process post
        from_user = User.objects.get(username=session.get('username'))
        to_user = User.objects.get(username=request.values.get('to_user'))
        post = form.post.data

        # if this is a self post
        if to_user == from_user:
            to_user = None
            
        # write the message
        message = Message(
            from_user=from_user,
            to_user=to_user,
            text=post,
            message_type=POST,
            ).save()
            
        # store on the same user's feed
        feed = Feed(
            user=from_user,
            message=message,
            ).save()
        
        # store images
        if len(post_images):
            images = []
            for file_path in post_images:
                (image_ts, width) = image_height_transform(file_path, 'posts', str(message.id))
                images.append({"ts": str(image_ts), "w": str(width)})
            message.images = images
            message.save()
            
        # process the message
        process_message(message)
        
        if ref:
            return redirect(ref)
        else:
            return redirect(url_for('home_routes.home'))

    else:
        return 'Error!'
        
@feed_app.route('/message/<message_id>', methods=('GET', 'POST'))
def message(message_id):
    form = FeedPostForm()
    message = None
    
    message = Message.objects.filter(id=message_id).first()
    if not message:
        abort(404)
        
    if message and message.parent:
        abort(404)
        
    if form.validate_on_submit() and session.get('username'):
        # process post
        from_user = User.objects.get(username=session.get('username'))
        post = form.post.data
        
        # write the message
        comment = Message(
            from_user=from_user,
            text=post,
            message_type=COMMENT,
            parent=message_id
            ).save()
            
        return redirect(url_for('feed_app.message', message_id=message.id))
            
    return render_template('feed/message.html',
        message=message,
        form=form
    )
    
@feed_app.route('/like/<message_id>', methods=('GET', 'POST'))
@login_required
def like_message(message_id):
    message = None

    message = Message.objects.filter(id=message_id).first()
    if not message:
        abort(404)
    
    if message and message.parent:
        abort(404)
        
    from_user = User.objects.get(username=session.get('username'))
    
    #check if first like
    existing_like = Message.objects.filter(
        parent=message_id,
        message_type=LIKE,
        from_user=from_user).count()

    if not existing_like:
        # write the like
        like = Message(
            from_user=from_user,
            to_user=message.from_user,
            message_type=LIKE,
            parent=message_id
            ).save()
        
    return redirect(url_for('feed_app.message', message_id=message.id))

user/routes.py
from flask import Blueprint, render_template, request, redirect, session, url_for, abort
import bcrypt
import uuid
import os
from werkzeug.utils import secure_filename
from mongoengine import Q

from user.models import User
from user.forms import RegisterForm, LoginForm, EditForm, ForgotForm, PasswordResetForm
from utilities.common import email
from settings import UPLOAD_FOLDER
from utilities.imaging import thumbnail_process
from relationship.models import Relationship
from user.decorators import login_required
from feed.forms import FeedPostForm
from feed.models import Message, POST

user_routes = Blueprint('user_routes', __name__)

@user_routes.route('/register', methods=('GET', 'POST'))
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        salt = bcrypt.gensalt()
        hashed_password = bcrypt.hashpw(form.password.data, salt)
        code = str(uuid.uuid4())
        user = User(
            username=form.username.data,
            password=hashed_password,
            email=form.email.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            change_configuration={
                "new_email": form.email.data.lower(),
                "confirmation_code": code
                }
            )

        # email the user
        body_html = render_template('mail/user/register.html', user=user)
        body_text = render_template('mail/user/register.txt', user=user)
        email(user.email, "Welcome to Flaskbook", body_html, body_text)

        user.save()
        return redirect(url_for('home_routes.home'))
    return render_template('user/register.html', form=form)

@user_routes.route('/login', methods=('GET', 'POST'))
def login():
    form = LoginForm()
    error = None

    if request.method == 'GET' and request.args.get('next'):
        session['next'] = request.args.get('next')

    if form.validate_on_submit():
        user = User.objects.filter(
            username=form.username.data
            ).first()
        if user:
            if bcrypt.hashpw(form.password.data, user.password) == user.password:
                session['username'] = form.username.data
                if 'next' in session:
                    next = session.get('next')
                    session.pop('next')
                    return redirect(next)
                else:
                    return redirect(url_for('home_routes.home'))
            else:
                user = None
        if not user:
            error = 'Incorrect credentials'
    return render_template('user/login.html', form=form, error=error)

@user_routes.route('/logout')
def logout():
    session.pop('username')
    return redirect(url_for('user_routes.login'))

@user_routes.route('/<username>/friends/<int:friends_page_number>', endpoint='profile-friends-page')
@user_routes.route('/<username>/friends', endpoint='profile-friends')
@user_routes.route('/<username>')
def profile(username, friends_page_number=1):
    logged_user = None
    rel = None
    friends_page = False
    user = User.objects.filter(username=username).first()
    profile_messages = []

    if user:
        if session.get('username'):
            logged_user = User.objects.filter(username=session.get('username')).first()
            rel = Relationship.get_relationship(logged_user, user)

        # get friends
        friends = Relationship.objects.filter(
            from_user=user,
            rel_type=Relationship.FRIENDS,
            status=Relationship.APPROVED
            )
        friends_total = friends.count()

        if 'friends' in request.url:
            friends_page = True
            friends = friends.paginate(page=friends_page_number, per_page=3)
        else:
            friends = friends[:5]

        form = FeedPostForm()

        # get user messages if friends or self
        if logged_user and (rel == "SAME" or rel == "FRIENDS_APPROVED"):
            profile_messages = Message.objects.filter(
                Q(from_user=user) | Q(to_user=user),
                message_type=POST
                ).order_by('-create_date')[:10]

        return render_template('user/profile.html',
            user=user,
            logged_user=logged_user,
            rel=rel,
            friends=friends,
            friends_total=friends_total,
            friends_page=friends_page,
            form=form,
            profile_messages=profile_messages
            )
    else:
        abort(404)

@user_routes.route('/edit', methods=('GET', 'POST'))
@login_required
def edit():
    error = None
    message = None
    user = User.objects.filter(username=session.get('username')).first()
    if user:
        form = EditForm(obj=user)
        if form.validate_on_submit():
            # check if image
            image_ts = None
            if request.files.get('image'):
                filename = secure_filename(form.image.data.filename)
                file_path = os.path.join(UPLOAD_FOLDER, 'user', filename)
                form.image.data.save(file_path)
                image_ts = str(thumbnail_process(file_path, 'user', str(user.id)))
            if user.username != form.username.data.lower():
                if User.objects.filter(username=form.username.data.lower()).first():
                    error = "Username already exists"
                else:
                    session['username'] = form.username.data.lower()
                    form.username.data = form.username.data.lower()
            if user.email != form.email.data.lower():
                if User.objects.filter(email=form.email.data.lower()).first():
                    error = "Email already exists"
                else:
                    code = str(uuid.uuid4())

                    user.change_configuration = {
                        "new_email": form.email.data.lower(),
                        "confirmation_code": code
                    }
                    user.email_confirmed = False
                    form.email.data = user.email
                    message = "You will need to confirm the new email to complete this change"

                    # email the user
                    body_html = render_template('mail/user/change_email.html', user=user)
                    body_text = render_template('mail/user/change_email.txt', user=user)
                    email(user.change_configuration['new_email'], "Confirm your new email", body_html, body_text)

            if not error:
                form.populate_obj(user)
                if image_ts:
                    user.profile_image = image_ts
                user.save()
                if not message:
                    message = "Profile updated"

        return render_template("user/edit.html", form=form, error=error, message=message, user=user)
    else:
        abort(404)

@user_routes.route('/confirm/<username>/<code>', methods=('GET', 'POST'))
def confirm(username, code):
    user = User.objects.filter(username=username).first()
    if user and user.change_configuration and user.change_configuration.get('confirmation_code'):
        if code == user.change_configuration.get('confirmation_code'):
            user.email = user.change_configuration.get('new_email')
            user.change_configuration = {}
            user.email_confirmed = True
            user.save()
            return render_template('user/email_confirmed.html')
    else:
        abort(404)

@user_routes.route('/forgot', methods=('GET', 'POST'))
def forgot():
    error = None
    message = None
    form = ForgotForm()
    if form.validate_on_submit():
        user = User.objects.filter(email=form.email.data.lower()).first()
        if user:
            code = str(uuid.uuid4())
            user.change_configuration={
                "password_reset_code": code
            }
            user.save()

            # email the user
            body_html = render_template('mail/user/password_reset.html', user=user)
            body_text = render_template('mail/user/password_reset.txt', user=user)
            email(user.email, "Password reset request", body_html, body_text)

        message = "You will receive a password reset email if we find that email in our system"
    return render_template('user/forgot.html', form=form, error=error, message=message)

@user_routes.route('/password_reset/<username>/<code>', methods=('GET', 'POST'))
def password_reset(username, code):
    message = None
    require_current = None

    form = PasswordResetForm()

    user = User.objects.filter(username=username).first()
    if not user or code != user.change_configuration.get('password_reset_code'):
        abort(404)

    if request.method == 'POST':
        del form.current_password
        if form.validate_on_submit():
            salt = bcrypt.gensalt()
            hashed_password = bcrypt.hashpw(form.password.data, salt)
            user.password = hashed_password
            user.change_configuration = {}
            user.save()

            if session.get('username'):
                session.pop('username')
            return redirect(url_for('user_routes.password_reset_complete'))

    return render_template('user/password_reset.html',
        form=form,
        message=message,
        require_current=require_current,
        username=username,
        code=code
    )

@user_routes.route('/password_reset_complete')
def password_reset_complete():
    return render_template('user/password_change_confirmed.html')

@user_routes.route('/change_password', methods=('GET', 'POST'))
def change_password():
    require_current = True
    error = None
    form = PasswordResetForm()

    user = User.objects.filter(username=session.get('username')).first()

    if not user:
        abort(404)

    if request.method == 'POST':
        if form.validate_on_submit():
            if bcrypt.hashpw(form.current_password.data, user.password) == user.password:
                salt = bcrypt.gensalt()

templates/feed/_feed_comments.html
{% macro render_feed_comment(comment) %}
<div class="media">
  <div class="media-left">
    <a href="{{ url_for('user_routes.profile', username=comment.from_user.username) }}">
      <img class="media-object" src="{{ comment.from_user.profile_imgsrc('sm') }}" width="25" height="25" alt="{{ comment.from_user.username }}">
    </a>
  </div> <!-- media-left -->
  <div class="media-body">
    <div class="media-user-pane">
      <span class="media-comment-user"><a href="{{ url_for('user_routes.profile', username=comment.from_user.username) }}">{{ comment.from_user.first_name }} {{ comment.from_user.last_name }}</a></span>
      <span class="media-comment-text">{{ comment.text_linkified|safe }}</span>
    </div>
    <div class="media-footer">
      <span class="media-timestamp">{{ comment.human_timestamp }}</span>
    </div> <!-- media-footer -->
  </div> <!-- media-body -->
</div> <!-- media -->
{% endmacro %}

templates/feed/_feed_messages.html
{% macro render_feed_message(message) %}
<div class="media">
  <div class="media-left">
    <a href="{{ url_for('user_routes.profile', username=message.from_user.username) }}">
      <img class="media-object" src="{{ message.from_user.profile_imgsrc('sm') }}" width="50" height="50" alt="{{ message.from_user.username }}">
    </a>
  </div> <!-- media-left -->
  <div class="media-body">
    <div class="media-user-pane">
      <span class="media-user"><a href="{{ url_for('user_routes.profile', username=message.from_user.username) }}">{{ message.from_user.first_name }} {{ message.from_user.last_name }}</a></span>
      {% if message.to_user %}
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> <span class="media-user"><a href="{{ url_for('user_routes.profile', username=message.to_user.username) }}">{{ message.to_user.first_name }} {{ message.to_user.last_name }}</a></span>
      {% endif %}
    </div>
    <div class="media-text">{{ message.text_linkified|safe }}</div>
    {% if message.images %}
    <div class="media-images">
    {% for image in message.images %}
      <img class="img-thumbnail" src="{{ message.post_imgsrc(image.ts, 'xlg') }}" width="{{ image.w }}" height="200" alt="" />
    {% endfor %}
    </div> <!-- media-images -->
    {% endif %}
    <div class="media-footer">
      <a href="{{ url_for('feed_app.message', message_id=message.id) }}" class="media-timestamp">
        {{ message.human_timestamp }}
      </a> - 
      <a href="{{ url_for('feed_app.message', message_id=message.id) }}#comment-form">Comment</a>
      {% if message.comments %}({{ message.comments.count() }}){% endif %}
       - <a href="{{ url_for('feed_app.like_message', message_id=message.id) }}">Like</a>
      {% if message.likes %}
      <div class="media-footer-likes">
          <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
          {% set comma = joiner(", ") %}
          {% for like in message.likes %}{{ comma() }}<a href="{{ url_for('user_routes.profile', username=like.from_user.username) }}">{{ like.from_user.username }}</a>{% endfor %}
      </div>
      {% endif %}
    </div>
  </div>
</div> <!-- media -->
{% endmacro %}

templates/feed/message.html
{% extends "base.html" %} 

{% block title %}{{ message.text[:50] }} - Flaskbook{% endblock %} 

{% block header %}<link href="{{ url_for('static', filename='css/base.css') }}" rel="stylesheet">{% endblock %}

{% block content %} 

{% include "navbar.html" %}

<div class="row">

  <div class="col-md-3">

  </div> <!-- col-md-3 -->
  
  <div class="col-md-9">
    
    <div class="row">
      
      <div class="col-md-9">

        <div class="row feed-message">          
        {% from "feed/_feed_messages.html" import render_feed_message %}
        {{ render_feed_message(message) }}
        </div> <!-- row feed-message -->

        <div class="row feed-message-comments">
          <div class="col-md-offset-1 col-md-9">
          {% from "feed/_feed_comments.html" import render_feed_comment %}
          {% for comment in message.comments %}
            {{ render_feed_comment(comment) }}
          {% endfor %}   

          </div> <!-- col-md-offset-1 col-md-9 -->
        </div> <!-- row feed-message-comments -->

        <!-- comment text input -->
        <div id="comment-form" class="row feed-comment">
          {% if error %}
          <div class="alert alert-danger" role="alert">{{ error }}</div>
          {% endif %}
      
          {% from "_formhelpers.html" import render_field %}
          <form method="POST" action="{{ url_for('feed_app.message', message_id=message.id)}}" role="form">
      
            {{ form.hidden_tag() }}
      
            <div class="form-group">
              {{ form.post(class='form-control', rows=2) }}
            </div>
            
            <input type="hidden" name="message_id" value="{{ message.id }}" />
            <button type="submit" class="btn btn-primary pull-right">Comment</button>
      
          </form>
        </div> <!-- row feed-comment -->
        <!-- post text input -->
        
      </div> <!-- col-md-9 -->
    
      <div class="col-md-3"> 
      
      </div> <!-- col-md-3 -->
    
  </div> <!-- col-md-9 -->

</div> <!-- row -->
{% endblock %}