user/forms.py
from flask_wtf import FlaskForm
from wtforms import validators, StringField, PasswordField
from wtforms.widgets import TextArea
from wtforms.fields.html5 import EmailField
from wtforms.validators import ValidationError
from flask_wtf.file import FileField, FileAllowed
import re

from user.models import User

class BaseUserForm(FlaskForm):
    first_name = StringField('First Name', [validators.DataRequired()])
    last_name = StringField('Last Name', [validators.DataRequired()])
    email = EmailField('Email address', [
        validators.DataRequired(),
        validators.Email()
        ]
    )
    username = StringField('Username', [
        validators.DataRequired(),
        validators.length(min=4, max=25)
        ])
    bio = StringField('Bio',
        widget=TextArea(),
        validators=[validators.Length(max=160)]
    )

class PasswordBaseForm(FlaskForm):
    password = PasswordField('New Password', [
        validators.DataRequired(),
        validators.EqualTo('confirm', message='Passwords must match'),
        validators.length(min=4, max=80)
        ])
    confirm = PasswordField('Repeat Password')

class RegisterForm(BaseUserForm, PasswordBaseForm):
    # Custom validator
    def validate_username(form, field):
        if User.objects.filter(username=field.data).first():
            raise ValidationError("Username already exists")
        if not re.match("^[a-zA-Z0-9_-]{4,25}$", field.data):
            raise ValidationError("Invalid username")

    def validate_email(form, field):
        if User.objects.filter(email=field.data).first():
            raise ValidationError("Email is already in use")

class LoginForm(FlaskForm):
    username = StringField('Username', [
        validators.DataRequired(),
        validators.length(min=4, max=25)
        ])
    password = PasswordField('Password', [
        validators.DataRequired(),
        validators.length(min=4, max=80)
        ])

class EditForm(BaseUserForm):
    image = FileField('Profile image', validators=[
        FileAllowed(['jpg', 'jpeg', 'png', 'gif'],
        'Only JPEG, PNG and GIFs allowed')
        ])

class ForgotForm(FlaskForm):
    email = EmailField('Email address',
        [validators.DataRequired(), validators.Email()]
    )

class PasswordResetForm(PasswordBaseForm):
    current_password = PasswordField('Current Password',
        [validators.DataRequired(),
        validators.Length(min=4, max=80)]
    )

feed/views.py
from flask import Blueprint, request, session, redirect, url_for, abort, render_template
from werkzeug import secure_filename
import os

from user.decorators import login_required
from user.models import User
from feed.models import Message, Feed, POST, COMMENT, LIKE
from feed.process import process_message
from feed.forms import FeedPostForm
from settings import UPLOAD_FOLDER
from utilities.imaging import image_height_transform

feed_app = Blueprint('feed_app', __name__)

@feed_app.route('/message/add', methods=('GET', 'POST'))
@login_required
def add_message():
    ref = request.referrer
    form = FeedPostForm()
    
    if form.validate_on_submit():
        # process images
        post_images = []
        uploaded_files = request.files.getlist('images')
        if uploaded_files and uploaded_files[0].filename != '':
            for file in uploaded_files:
                filename = secure_filename(file.filename)
                file_path = os.path.join(UPLOAD_FOLDER, 'posts', filename)
                file.save(file_path)
                post_images.append(file_path)
                
        # process post
        from_user = User.objects.get(username=session.get('username'))
        to_user = User.objects.get(username=request.values.get('to_user'))
        post = form.post.data

        # if this is a self post
        if to_user == from_user:
            to_user = None
            
        # write the message
        message = Message(
            from_user=from_user,
            to_user=to_user,
            text=post,
            message_type=POST,
            ).save()
            
        # store on the same user's feed
        feed = Feed(
            user=from_user,
            message=message,
            ).save()
        
        # store images
        if len(post_images):
            images = []
            for file_path in post_images:
                (image_ts, width) = image_height_transform(file_path, 'posts', str(message.id))
                images.append({"ts": str(image_ts), "w": str(width)})
            message.images = images
            message.save()
            
        # process the message
        process_message(message)
        
        if ref:
            return redirect(ref)
        else:
            return redirect(url_for('home_routes.home'))

    else:
        return 'Error!'
        
@feed_app.route('/message/<message_id>', methods=('GET', 'POST'))
def message(message_id):
    form = FeedPostForm()
    message = None
    
    message = Message.objects.filter(id=message_id).first()
    if not message:
        abort(404)
        
    if message and message.parent:
        abort(404)
        
    if form.validate_on_submit() and session.get('username'):
        # process post
        from_user = User.objects.get(username=session.get('username'))
        post = form.post.data
        
        # write the message
        comment = Message(
            from_user=from_user,
            text=post,
            message_type=COMMENT,
            parent=message_id
            ).save()
            
        return redirect(url_for('feed_app.message', message_id=message.id))
            
    return render_template('feed/message.html',
        message=message,
        form=form
    )
    
@feed_app.route('/like/<message_id>', methods=('GET', 'POST'))
@login_required
def like_message(message_id):
    message = None

    message = Message.objects.filter(id=message_id).first()
    if not message:
        abort(404)
    
    if message and message.parent:
        abort(404)
        
    from_user = User.objects.get(username=session.get('username'))
    
    #check if first like
    existing_like = Message.objects.filter(
        parent=message_id,
        message_type=LIKE,
        from_user=from_user).count()

    if not existing_like:
        # write the like
        like = Message(
            from_user=from_user,
            to_user=message.from_user,
            message_type=LIKE,
            parent=message_id
            ).save()
        
    return redirect(url_for('feed_app.message', message_id=message.id))

user/routes.py
from flask import Blueprint, render_template, request, redirect, session, url_for, abort
import bcrypt
import uuid
import os
from werkzeug.utils import secure_filename
from mongoengine import Q

from user.models import User
from user.forms import RegisterForm, LoginForm, EditForm, ForgotForm, PasswordResetForm
from utilities.common import email
from settings import UPLOAD_FOLDER
from utilities.imaging import thumbnail_process
from relationship.models import Relationship
from user.decorators import login_required
from feed.forms import FeedPostForm
from feed.models import Message, POST

user_routes = Blueprint('user_routes', __name__)

@user_routes.route('/register', methods=('GET', 'POST'))
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        salt = bcrypt.gensalt()
        hashed_password = bcrypt.hashpw(form.password.data, salt)
        code = str(uuid.uuid4())
        user = User(
            username=form.username.data,
            password=hashed_password,
            email=form.email.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            change_configuration={
                "new_email": form.email.data.lower(),
                "confirmation_code": code
                }
            )

        # email the user
        body_html = render_template('mail/user/register.html', user=user)
        body_text = render_template('mail/user/register.txt', user=user)
        email(user.email, "Welcome to Flaskbook", body_html, body_text)

        user.save()
        return redirect(url_for('home_routes.home'))
    return render_template('user/register.html', form=form)

@user_routes.route('/login', methods=('GET', 'POST'))
def login():
    form = LoginForm()
    error = None

    if request.method == 'GET' and request.args.get('next'):
        session['next'] = request.args.get('next')

    if form.validate_on_submit():
        user = User.objects.filter(
            username=form.username.data
            ).first()
        if user:
            if bcrypt.hashpw(form.password.data, user.password) == user.password:
                session['username'] = form.username.data
                if 'next' in session:
                    next = session.get('next')
                    session.pop('next')
                    return redirect(next)
                else:
                    return redirect(url_for('home_routes.home'))
            else:
                user = None
        if not user:
            error = 'Incorrect credentials'
    return render_template('user/login.html', form=form, error=error)

@user_routes.route('/logout')
def logout():
    session.pop('username')
    return redirect(url_for('user_routes.login'))

@user_routes.route('/<username>/friends/<int:friends_page_number>', endpoint='profile-friends-page')
@user_routes.route('/<username>/friends', endpoint='profile-friends')
@user_routes.route('/<username>')
def profile(username, friends_page_number=1):
    logged_user = None
    rel = None
    friends_page = False
    user = User.objects.filter(username=username).first()
    profile_messages = []

    if user:
        if session.get('username'):
            logged_user = User.objects.filter(username=session.get('username')).first()
            rel = Relationship.get_relationship(logged_user, user)

        # get friends
        friends = Relationship.objects.filter(
            from_user=user,
            rel_type=Relationship.FRIENDS,
            status=Relationship.APPROVED
            )
        friends_total = friends.count()

        if 'friends' in request.url:
            friends_page = True
            friends = friends.paginate(page=friends_page_number, per_page=3)
        else:
            friends = friends[:5]

        form = FeedPostForm()

        # get user messages if friends or self
        if logged_user and (rel == "SAME" or rel == "FRIENDS_APPROVED"):
            profile_messages = Message.objects.filter(
                Q(from_user=user) | Q(to_user=user),
                message_type=POST
                ).order_by('-create_date')[:10]

        return render_template('user/profile.html',
            user=user,
            logged_user=logged_user,
            rel=rel,
            friends=friends,
            friends_total=friends_total,
            friends_page=friends_page,
            form=form,
            profile_messages=profile_messages
            )
    else:
        abort(404)

@user_routes.route('/edit', methods=('GET', 'POST'))
@login_required
def edit():
    error = None
    message = None
    user = User.objects.filter(username=session.get('username')).first()
    if user:
        form = EditForm(obj=user)
        if form.validate_on_submit():
            # check if image
            image_ts = None
            if request.files.get('image'):
                filename = secure_filename(form.image.data.filename)
                file_path = os.path.join(UPLOAD_FOLDER, 'user', filename)
                form.image.data.save(file_path)
                image_ts = str(thumbnail_process(file_path, 'user', str(user.id)))
            if user.username != form.username.data.lower():
                if User.objects.filter(username=form.username.data.lower()).first():
                    error = "Username already exists"
                else:
                    session['username'] = form.username.data.lower()
                    form.username.data = form.username.data.lower()
            if user.email != form.email.data.lower():
                if User.objects.filter(email=form.email.data.lower()).first():
                    error = "Email already exists"
                else:
                    code = str(uuid.uuid4())

                    user.change_configuration = {
                        "new_email": form.email.data.lower(),
                        "confirmation_code": code
                    }
                    user.email_confirmed = False
                    form.email.data = user.email
                    message = "You will need to confirm the new email to complete this change"

                    # email the user
                    body_html = render_template('mail/user/change_email.html', user=user)
                    body_text = render_template('mail/user/change_email.txt', user=user)
                    email(user.change_configuration['new_email'], "Confirm your new email", body_html, body_text)

            if not error:
                form.populate_obj(user)
                if image_ts:
                    user.profile_image = image_ts
                user.save()
                if not message:
                    message = "Profile updated"

        return render_template("user/edit.html", form=form, error=error, message=message, user=user)
    else:
        abort(404)

@user_routes.route('/confirm/<username>/<code>', methods=('GET', 'POST'))
def confirm(username, code):
    user = User.objects.filter(username=username).first()
    if user and user.change_configuration and user.change_configuration.get('confirmation_code'):
        if code == user.change_configuration.get('confirmation_code'):
            user.email = user.change_configuration.get('new_email')
            user.change_configuration = {}
            user.email_confirmed = True
            user.save()
            return render_template('user/email_confirmed.html')
    else:
        abort(404)

@user_routes.route('/forgot', methods=('GET', 'POST'))
def forgot():
    error = None
    message = None
    form = ForgotForm()
    if form.validate_on_submit():
        user = User.objects.filter(email=form.email.data.lower()).first()
        if user:
            code = str(uuid.uuid4())
            user.change_configuration={
                "password_reset_code": code
            }
            user.save()

            # email the user
            body_html = render_template('mail/user/password_reset.html', user=user)
            body_text = render_template('mail/user/password_reset.txt', user=user)
            email(user.email, "Password reset request", body_html, body_text)

        message = "You will receive a password reset email if we find that email in our system"
    return render_template('user/forgot.html', form=form, error=error, message=message)

@user_routes.route('/password_reset/<username>/<code>', methods=('GET', 'POST'))
def password_reset(username, code):
    message = None
    require_current = None

    form = PasswordResetForm()

    user = User.objects.filter(username=username).first()
    if not user or code != user.change_configuration.get('password_reset_code'):
        abort(404)

    if request.method == 'POST':
        del form.current_password
        if form.validate_on_submit():
            salt = bcrypt.gensalt()
            hashed_password = bcrypt.hashpw(form.password.data, salt)
            user.password = hashed_password
            user.change_configuration = {}
            user.save()

            if session.get('username'):
                session.pop('username')
            return redirect(url_for('user_routes.password_reset_complete'))

    return render_template('user/password_reset.html',
        form=form,
        message=message,
        require_current=require_current,
        username=username,
        code=code
    )

@user_routes.route('/password_reset_complete')
def password_reset_complete():
    return render_template('user/password_change_confirmed.html')

@user_routes.route('/change_password', methods=('GET', 'POST'))
def change_password():
    require_current = True
    error = None
    form = PasswordResetForm()

    user = User.objects.filter(username=session.get('username')).first()

    if not user:
        abort(404)

    if request.method == 'POST':
        if form.validate_on_submit():
            if bcrypt.hashpw(form.current_password.data, user.password) == user.password:
                salt = bcrypt.gensalt()

templates/user/_rel_button.html
{% macro rel_button(rel, user) %}

{% if rel == "SAME" %}
    <a href="{{ url_for('.edit') }}" role="button" class="btn btn-default">
    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
    Edit profile
    </a>
{% endif %}

{% if rel == None %}
<a href="{{ url_for('relationship_app.add_friend', to_username=user.username) }}" role="button" class="relationship-add-friend btn btn-default">
  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add Friend
</a>  
<a href="{{ url_for('relationship_app.block', to_username=user.username) }}" role="button" class="btn btn-default">
  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Block
</a>  
{% endif %}

{% if rel == "BLOCKED" %}
<a href="{{ url_for('relationship_app.unblock', to_username=user.username) }}" role="button" class="relationship-blocked btn btn-danger">
  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> <span id="relationship-label">Blocked</span>
</a>
{% endif %}

{% if rel == "FRIENDS_APPROVED" %}
<a href="{{ url_for('relationship_app.remove_friend', to_username=user.username) }}" role="button" class="relationship-friends btn btn-primary">
  <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> <span id="relationship-label">Friends</span>
</a>
{% endif %}

{% if rel == "FRIENDS_PENDING" %}
<a href="{{ url_for('relationship_app.remove_friend', to_username=user.username) }}" role="button" class="relationship-friends-requested btn btn-primary">
  <span class="glyphicon glyphicon-user" aria-hidden="true"></span> <span id="relationship-label">Friendship Requested</span>
</a>
{% endif %}

{% if rel == "REVERSE_FRIENDS_PENDING" %}
<a href="{{ url_for('relationship_app.add_friend', to_username=user.username) }}" role="button" class="relationship-reverse-friends-requested btn btn-primary">
  <span class="glyphicon glyphicon-user" aria-hidden="true"></span> <span id="relationship-label">Accept Friendship</span>
</a>
<a href="{{ url_for('relationship_app.remove_friend', to_username=user.username) }}" role="button" class="relationship-reverse-friends-cancel btn btn-default">
  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> <span id="relationship-label">Deny Friendship</span>
</a>            
{% endif %}

{% if rel == "REVERSE_BLOCKED" %}
  <a href="#" class="relationship-reverse-blocked"></a>
{% endif %}
{% endmacro %}

{% macro rel_js() %}
<script type="text/javascript">
$(document).ready(function(){
  $('.relationship-friends').mouseover(function() {
    $(this).find('.relationship-label').text('Unfriend');
    $(this).attr("class", "btn btn-default");
  }).mouseout(function(){
    $(this).find('.relationship-label').text('Friends');
    $(this).attr("class", "btn btn-primary");
  });            
});
$(document).ready(function(){
  $('.relationship-blocked').mouseover(function() {
    $(this).find('.relationship-label').text('Unblock');
    $(this).attr("class", "btn btn-default");
  }).mouseout(function(){
    $(this).find('.relationship-label').text('Blocked');
    $(this).attr("class", "btn btn-danger");
  });            
});
$(document).ready(function(){
  $('.relationship-friends-requested').mouseover(function() {
    $(this).find('.relationship-label').text('Cancel Friend Request');
    $(this).attr("class", "btn btn-danger");
  }).mouseout(function(){
    $(this).find('.relationship-label').text('Friendship Requested');
    $(this).attr("class", "btn btn-primary");
  });            
});
</script>
{% endmacro %}

templates/user/edit.html
{% extends "base.html" %}

{% block title %}Edit profile{% endblock %}

{% block content %}

{% include "navbar.html" %}

<div class="row">

  <div class="col-md-offset-3 col-md-6">

    <h3>Edit Profile</h3>

    {% if error %}
    <div class="alert alert-danger" role="alert">{{ error }}</div>
    {% endif %}

    {% if message %}
    <div class="alert alert-success" role="alert">{{ message }}</div>
    {% endif %}

    {% from "_formhelpers.html" import render_field %}
    <form method="POST" action="{{ url_for('.edit')}}" role="form" enctype="multipart/form-data">

      {{ form.hidden_tag() }}

      {% if user.profile_image %}
      <div class="thumbnail">
        <img src="{{ user.profile_imgsrc('xlg') }}" class="img-rounded">
      </div>
      {% endif %}

      {{ render_field(form.image, class='form-control') }}

      {{ render_field(form.first_name, class='form-control') }}
      {{ render_field(form.last_name, class='form-control') }}

      {{ render_field(form.username, class='form-control') }}
      {{ render_field(form.email, class='form-control') }}

      {{ render_field(form.bio, maxlength="160", rows="3", class='form-control') }}

      <button type="submit" class="btn btn-default">Save</button>

    </form>

  </div>

</div>
{% endblock %}

templates/user/email_confirmed.html
{% extends "base.html" %}

{% block title %}Email confirmed{% endblock %}

{% block content %}

{% include "navbar.html" %}

<div class="row">

  <div class="col-md-offset-3 col-md-6">
    
    <div class="well well-lg">Your email has been confirmed</div>
    
  </div>

</div>

{% endblock %}

templates/user/forgot.html
{% extends "base.html" %}

{% block title %}Forgot password{% endblock %}

{% block content %}

{% include "navbar.html" %}

<div class="row">

  <div class="col-md-offset-3 col-md-6">
    
    <h3>Forgot password</h3>
    
    <p>Please enter your email address and we will send a password reset link to your email.</p>

    {% if error %}
    <div class="alert alert-danger" role="alert">{{ error }}</div>
    {% endif %}
    
    {% if message %}
    <div class="alert alert-success" role="alert">{{ message }}</div>
    {% endif %}

    {% from "_formhelpers.html" import render_field %}
    <form method="POST" action="{{ url_for('.forgot')}}" role="form">

      {{ form.hidden_tag() }}

      {{ render_field(form.email, class='form-control') }}

      <button type="submit" class="btn btn-default">Reset password</button>

    </form>

  </div>

</div>
{% endblock %}

templates/user/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}

{% include "navbar.html" %}

<div class="row">

  <div class="col-md-offset-3 col-md-6">

    <h3>User Login</h3>

    {% if error %}
    <div class="alert alert-danger" role="alert">{{ error }}</div>
    {% endif %}

    {% from "_formhelpers.html" import render_field %}
    <form method="POST" action="{{ url_for('.login')}}" role="form">

      {{ form.hidden_tag() }}

      {{ render_field(form.username, class='form-control') }}
      {{ render_field(form.password, class='form-control') }}

      <button type="submit" class="btn btn-default">Login</button>

    </form>

  </div>

</div>
{% endblock %}

templates/user/password_change_confirmed.html
{% extends "base.html" %}

{% block title %}Password change confirmed{% endblock %}

{% block content %}

{% include "navbar.html" %}

<div class="row">

  <div class="col-md-offset-3 col-md-6">
    
    <div class="well well-lg">Your password has been updated. Please <a href="{{ url_for('user_routes.login') }}">login</a> using your new passwword.</div>
    
  </div>

</div>

{% endblock %}

templates/user/password_reset.html
{% extends "base.html" %}

{% block title %}Password reset{% endblock %}

{% block content %}

{% include "navbar.html" %}

<div class="row">

  <div class="col-md-offset-3 col-md-6">
    
    <h3>Password reset</h3>

    {% if error %}
    <div class="alert alert-danger" role="alert">{{ error }}</div>
    {% endif %}
    
    {% if message %}
    <div class="alert alert-success" role="alert">{{ message }}</div>
    {% endif %}

    {% from "_formhelpers.html" import render_field %}
      {% if require_current %}
        <form method="POST" action="{{ url_for('.change_password')}}" role="form">
      {% else %}
        <form method="POST" action="{{ url_for('.password_reset', username=username, code=code)}}" role="form">
      {% endif %}

      {{ form.hidden_tag() }}

      {% if require_current %}
      {{ render_field(form.current_password, class='form-control') }}
      {% endif %}
  
      {{ render_field(form.password, class='form-control') }}
      
      {{ render_field(form.confirm, class='form-control') }}

      <button type="submit" class="btn btn-default">Save new password</button>

    </form>

  </div>

</div>
{% endblock %}

templates/user/profile.html
{% extends "base.html" %}
{% from "user/_rel_button.html" import rel_button, rel_js %}

{% block title %}{{ user.username }} - Profile{% endblock %}

{% block header %}<link href="{{ url_for('static', filename='css/base.css') }}" rel="stylesheet">{% endblock %}

{% block content %}

{% include "navbar.html" %}

<div class="row">

  <div class="col-md-3">

    <img class="img-thumbnail" src="{{ user.profile_imgsrc('xlg') }}" width="200" height="200" alt="{{ user.username }}">

    <h3 class="profile-fullname">{{ user.first_name }} {{ user.last_name }}</h3>
    <h3 class="profile-username"><a href="{{ url_for('user_routes.profile', username=user.username) }}" />@{{ user.username }}</a></h3>

  </div> <!-- col-md-3 -->

  <div class="col-md-9">

    <div id="friends-toolbar" class="row">

      <div class="btn-toolbar pull-right" role="toolbar" aria-label="friends-toolbar">
        <div class="btn-group" role="group" aria-label="friends-toolbar-buttons">
          {{ rel_button(rel, user) }}
        </div> <!-- btn-group -->
      </div> <!-- btn-toolbar -->

    </div> <!-- friends-toolbar -->

    <div class="row">

      {% if not friends_page %}

      <div class="col-md-9">

        {% if logged_user and (rel == "FRIENDS_APPROVED" or logged_user == user) %}
        <!-- post text input -->
        <div class="row feed-message">
          {% if error %}
          <div class="alert alert-danger" role="alert">{{ error }}</div>
          {% endif %}

          {% from "_formhelpers.html" import render_field %}
          <form method="POST" action={{ url_for('feed_app.add_message') }} role="form">
            {{ form.hidden_tag() }}

            <div class="form-group">
              {{ form.images(class='form-control') }}
              {{ form.post(class='form-control', rows=3) }}
            </div>

            <input type="hidden" name="to_user" value="{{ user.username }}" />
            <button type="submit" class="btn btn-primary pull-right">Post</button>

          </form>
          </div> <!-- feed-message -->
          <!-- post text input -->
          {% endif %}

          {% from "feed/_feed_messages.html" import render_feed_message %}
          {% for message in profile_messages %}
            {{ render_feed_message(message) }}
          {% endfor %}

      </div> <!-- col-md-9 -->

      <div class="col-md-3"> <!-- Friends side bar -->

        <h4><span class="glyphicon glyphicon-user" aria-hidden="true"></span>
          <a href="{{ url_for('.profile-friends', username=user.username) }}">Friends</a>
        <span class="badge">{{ friends_total }}</span></h4>

        {% for friend in friends %}
        <div class="media">
          <div class="media-left">
            <a class="img-thumnbnail" href="{{ url_for('.profile', username=friend.to_user.username) }}">
              <img class="media-object" src="{{ friend.to_user.profile_imgsrc('sm') }}" width="50" height="50" alt="{{ friend.to_user.username }}">
            </a>
          </div>
          <div class="media-body">
            <p>{{ friend.to_user.first_name }}<br />
              <a href="{{ url_for('.profile', username=friend.to_user.username) }}">@{{ friend.to_user.username }}</a>
            </p>
          </div>
        </div> <!-- media -->
        {% endfor %}

      </div> <!-- Friends side bar -->

      {% else %}

      <div class="col-md-12"> <!-- == Friend list == -->

        <div class="row">

          {% for friend in friends.items %}

            <div class="col-md-3 friend-grid-user">
              <div class="friend-grid-user-image">
                <a class="img-thumbnail" href="{{ url_for('.profile', username=friend.to_user.username) }}">
                  <img src="{{ friend.to_user.profile_imgsrc('lg') }}" width="75" alt="{{ friend.to_user.username }}">
                </a>
              </div>
              <div class="friend-grid-user-data">
                <h4 class="profile-fullname">{{ friend.to_user.first_name }} {{ friend.to_user.last_name }} </h5>
                <h5 class="profile-username"><a href="{{ url_for('.profile', username=friend.to_user.username) }}">@{{ friend.to_user.username }}</a></h4>
              </div>
              <div class="friend-grid-user-friends-button">
                {{ rel_button(friend.is_friend(logged_user), friend.to_user) }}
              </div>
            </div> <!-- col-md-3 -->

          {% endfor %}

        </div> <!-- row -->

      </div> <!-- col-md-12 -->

      <div class="profile-friends-pagination col-md-12"> <!-- == Pagination == -->

        <div class="row">

          <div class="col-md-6 pull-left">
          {% if friends.has_prev %}
          <a role="button" class="btn btn-primary" href="{{ url_for('.profile-friends-page', username=user.username, friends_page_number=friends.prev_num) }}">< Previous</a>
          {% endif %}
          </div> <!-- col-md-6 -->

          <div class="col-md-6 pull-right">
          {% if friends.has_next %}
          <a class="btn btn-primary" href="{{ url_for('.profile-friends-page', username=user.username, friends_page_number=friends.next_num) }}">Next ></a>
          {% endif %}
          </div> <!-- col-md-6 -->

        </div> <!-- row -->

      </div>

      {% endif %}

    </div> <!-- row -->

  </div> <!-- col-md-9 -->

</div>
{% endblock %}

{% block end_body_js %}
{{ rel_js() }}
{% endblock %}

templates/user/register.html
{% extends "base.html" %}

{% block title %}Registration{% endblock %}

{% block content %}

{% include "navbar.html" %}

<div class="row">

  <div class="col-md-offset-3 col-md-6">

    <h3>Registration</h3>

    {% from "_formhelpers.html" import render_field %}
    <form method="POST" action="{{ url_for('.register')}}" role="form">

      {{ form.hidden_tag() }}

      {{ render_field(form.first_name, class='form-control') }}
      {{ render_field(form.last_name, class='form-control') }}

      {{ render_field(form.username, class='form-control') }}
      {{ render_field(form.email, class='form-control') }}

      {{ render_field(form.password, class='form-control') }}
      {{ render_field(form.confirm, class='form-control') }}

      <button type="submit" class="btn btn-default">Register</button>

    </form>

  </div>

</div>
{% endblock %}